package types

// DONTCOVER

import (
	sdkerrors "github.com/cosmos/cosmos-sdk/types/errors"
)

// x/blockchainchat module sentinel errors
var (
	CopyrightNotFoundErr         = sdkerrors.Register(ModuleName, 101, "版权信息未找到")
	BalanceErr                   = sdkerrors.Register(ModuleName, 102, "余额错误")
	CopyrightPartyNotFoundErr    = sdkerrors.Register(ModuleName, 103, "版权方信息未找到")
	RDSNotFoundErr               = sdkerrors.Register(ModuleName, 104, "RDS信息未找到")
	DeflationVoteOptionErr       = sdkerrors.Register(ModuleName, 105, "通缩投票选项不合法")
	DeflationVoted               = sdkerrors.Register(ModuleName, 106, "已经投票")
	TokenidNotExist              = sdkerrors.Register(ModuleName, 107, "nft不存在")
	TokenidHasNoRight            = sdkerrors.Register(ModuleName, 108, "无权操作当前nft")
	TokenidFormatErr             = sdkerrors.Register(ModuleName, 109, "nft数据格式化失败")
	MortgMinerHasFinish          = sdkerrors.Register(ModuleName, 110, "抵押挖矿已经完成")
	ErrDataHashDoesNotExist      = sdkerrors.Register(ModuleName, 111, "datahash 不存在")
	AccuseAccountInvalid         = sdkerrors.Register(ModuleName, 112, "版权申述账号不合法")
	ComplainIdInvalid            = sdkerrors.Register(ModuleName, 113, "版权申述id不合法")
	ErrComplainStatusInvalid     = sdkerrors.Register(ModuleName, 114, "版权申述状态不合法")
	ErrResponseStatusInvalid     = sdkerrors.Register(ModuleName, 115, "版权申述回复状态不合法")
	ErrComplainDoesNotExist      = sdkerrors.Register(ModuleName, 116, "版权申述不存在")
	ErrComplainFinished          = sdkerrors.Register(ModuleName, 126, "版权申述投票已结束")
	ErrAccountHasNoVoteRight     = sdkerrors.Register(ModuleName, 127, "当前账号没有投票权")
	ErrInvalidContributionValue  = sdkerrors.Register(ModuleName, 128, "下载贡献值无效")
	ErrComplainVoteStatusInvalid = sdkerrors.Register(ModuleName, 129, "版权申述投票状态不合法")
	HasVoted                     = sdkerrors.Register(ModuleName, 130, "当前账号已投票")
	VerificationError            = sdkerrors.Register(ModuleName, 131, "验签失败")
	PubkeyNotExist               = sdkerrors.Register(ModuleName, 132, "公钥地址不存在")
	InviteCodeNotExist           = sdkerrors.Register(ModuleName, 133, "邀请码错误")
	AccountSpaceReturnError      = sdkerrors.Register(ModuleName, 134, "存储空间返还失败")
	AccountSpaceNotEnough        = sdkerrors.Register(ModuleName, 135, "存储空间不足")
	NoSpaceMinerRewardErr        = sdkerrors.Register(ModuleName, 136, "没有待领取的挖矿收益")
	OnlyMainTokenErr             = sdkerrors.Register(ModuleName, 137, "仅支持主币挖矿")
	TokenIdEmpty                 = sdkerrors.Register(ModuleName, 138, "tokenid 不能为空")
	TokenidApprovehasExist       = sdkerrors.Register(ModuleName, 139, "tokenId approve has exist")
	TokenidNotEmpty              = sdkerrors.Register(ModuleName, 140, "tokenId not empty")
	TokenidHasNoDrawRight        = sdkerrors.Register(ModuleName, 141, "tokenId has no draw right")
	TokenidHasExist              = sdkerrors.Register(ModuleName, 142, "tokenId has exist")
	SpaceSettlementErr           = sdkerrors.Register(ModuleName, 143, "奖励空间结算失败")
	CopyrightMortgageErr         = sdkerrors.Register(ModuleName, 144, "版权抵押无效")
	UnAuthorizedAccountError     = sdkerrors.Register(ModuleName, 145, "未授权的账号")
	CopyrightAccountError        = sdkerrors.Register(ModuleName, 146, "版权归属不一致")
	SpaceFirstError              = sdkerrors.Register(ModuleName, 147, "请先兑换空间")
	CopyrightComplainErr         = sdkerrors.Register(ModuleName, 148, "当前版权申述中")
	CopyrightVoteInvalidErr      = sdkerrors.Register(ModuleName, 149, "版权投票无效")
	CopyrightVoteNotEnoughErr    = sdkerrors.Register(ModuleName, 150, "版权投票数不足")
	CopyrightApproveHasFinished  = sdkerrors.Register(ModuleName, 151, "版权审核投票已结束")
	FeeInvalidErr                = sdkerrors.Register(ModuleName, 152, "fee amount is invalid")
)
